export const stack = [
  'JavaScript (ES6+)',
  'TypeScript',
  'React.js',
  'Next.js',
  'Tailwind CSS',
  'Supabase',
  'OpenAI API',
  'Fabric.js',
  'Canvas API',
  'RESTful APIs',
  'Shadcn/ui',
  'Styled Components',
  'Framer Motion',
  'Axios',
  'Zustand',
  'Git & GitHub',
  'Figma',
  'Postman',
  'Vercel',
  'VS Code',
];
